### ISSUE TITLE
Text too small, what can I do?

### ISSUE THREAD

**Issue by BAMBROISE-LO** [JohnCoene/tippy#5]
Hi there :)

Just discovered this tool and it is really great! 
I have a quick question though.
I'm using the tooltip as follow: 
`tippy("Hover me!", tooltip = "put help text here")`

I'm using it on a markdown page with the rmdformats library (using the templates material). and my issue is that the size of the text is very small. Is there something that I can do to change that? 

Many thanks!

**Comment by JohnCoene** [comment]
I reckon the easiest way is probably to use some CSS since the tooltip accepts HTML, perhaps the `size` parameter may also help. 

```r
tippy("hover", "<strong>Bolded content</strong>", size = "large")
```

If you need to do it on a lot of tooltips you can use a class.

In the CSS

```css
.tooltip{
  font-size:25px;
}
```

In R.

```r
tippy("hover", "<span class='tooltip'>Bolded content</span>")
```

One of the issues here is that tippy is poorly documented, all the options are documented [here](https://atomiks.github.io/tippyjs/all-options/).
